/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Control;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifgdias
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    
    public Janela() {        
        initComponents();
        c = new Control(this);
    }

    public JButton getBtn_Limpar() {
        return Btn_Limpar;
    }

    public void setBtn_Limpar(JButton Btn_Limpar) {
        this.Btn_Limpar = Btn_Limpar;
    }

    public JButton getBtn_Somar() {
        return Btn_Somar;
    }

    public void setBtn_Somar(JButton Btn_Somar) {
        this.Btn_Somar = Btn_Somar;
    }

    public JLabel getLbl_1() {
        return Lbl_1;
    }

    public void setLbl_1(JLabel Lbl_1) {
        this.Lbl_1 = Lbl_1;
    }

    public JLabel getLbl_2() {
        return Lbl_2;
    }

    public void setLbl_2(JLabel Lbl_2) {
        this.Lbl_2 = Lbl_2;
    }

    public JLabel getLbl_3() {
        return Lbl_3;
    }

    public void setLbl_3(JLabel Lbl_3) {
        this.Lbl_3 = Lbl_3;
    }

    public JTextField getTxt_Num1() {
        return Txt_Num1;
    }

    public void setTxt_Num1(JTextField Txt_Num1) {
        this.Txt_Num1 = Txt_Num1;
    }

    public JTextField getTxt_Num2() {
        return Txt_Num2;
    }

    public void setTxt_Num2(JTextField Txt_Num2) {
        this.Txt_Num2 = Txt_Num2;
    }

    public JTextField getTxt_Num3() {
        return Txt_Num3;
    }

    public void setTxt_Num3(JTextField Txt_Num3) {
        this.Txt_Num3 = Txt_Num3;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_1 = new javax.swing.JLabel();
        Txt_Num1 = new javax.swing.JTextField();
        Lbl_2 = new javax.swing.JLabel();
        Txt_Num2 = new javax.swing.JTextField();
        Lbl_3 = new javax.swing.JLabel();
        Txt_Num3 = new javax.swing.JTextField();
        Btn_Limpar = new javax.swing.JButton();
        Btn_Somar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Somar Números");

        Lbl_1.setText("Número 1: ");

        Txt_Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Num1ActionPerformed(evt);
            }
        });

        Lbl_2.setText("Número 2: ");

        Txt_Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Num2ActionPerformed(evt);
            }
        });

        Lbl_3.setText("Resultado: ");

        Btn_Limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Limpar.setText("Limpar");
        Btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimparActionPerformed(evt);
            }
        });

        Btn_Somar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Btn_Somar.setText("Somar");
        Btn_Somar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SomarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Somar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_3)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_2)
                            .addGap(18, 18, 18)
                            .addComponent(Txt_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Lbl_1)
                            .addGap(18, 18, 18)
                            .addComponent(Txt_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_1)
                    .addComponent(Txt_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_2)
                    .addComponent(Txt_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_3)
                    .addComponent(Txt_Num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Limpar)
                    .addComponent(Btn_Somar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Num2ActionPerformed

    private void Btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimparActionPerformed
        c.controlLimpar();
    }//GEN-LAST:event_Btn_LimparActionPerformed

    private void Btn_SomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SomarActionPerformed
        c.controlSomar();
    }//GEN-LAST:event_Btn_SomarActionPerformed

    private void Txt_Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_Num1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }
    
    
    private Control c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Limpar;
    private javax.swing.JButton Btn_Somar;
    private javax.swing.JLabel Lbl_1;
    private javax.swing.JLabel Lbl_2;
    private javax.swing.JLabel Lbl_3;
    private javax.swing.JTextField Txt_Num1;
    private javax.swing.JTextField Txt_Num2;
    private javax.swing.JTextField Txt_Num3;
    // End of variables declaration//GEN-END:variables
}
